### ISSUE TITLE
Filter search results

### ISSUE THREAD

**Issue by cdsnl** [Servoy/svyLookup#1]
Hi

Thanks Sean for the create module and the webinar yesterday.
I have a question about this module. I would like to make sure that the user only can search for particular records. In this case only the records where the record_status='A'. So the use can not search for or select a record where the record_status is something else then an 'A'.

I tried the code below. But I can still search and select all records.

Should I use table filters or is there another way.

Thanks
Andre

	var query = datasources.db.cds.company.createSelect();
	query.result.addPk();
	query.where.add(query.columns.record_status.eq('A'));
	query.sort.add(query.columns.name);
	var fs = datasources.db.cds.company.getFoundSet();
	fs.loadRecords(query);
	var lookupObj = scopes.svyLookup.createLookup(fs);

**Comment by paronne** [comment]
With the commit https://github.com/Servoy/svyLookup/commit/4fbdc18aa357b090f83865bae6fedb2e5467c954
will be possible to filter the result set by adding foundset filters to the original foundset.

```	
        var fs = datasources.db.example_data.products.getFoundSet();
	fs.addFoundSetFilterParam("unitprice",">","30","unitprice-filter");
	fs.sort("unitprice desc", true);
        var lookupObj = scopes.svyLookup.createLookup(fs);```
