### ISSUE TITLE
Translate Placeholder-Text

### ISSUE THREAD

**Issue by philippr71** [Servoy/svyLookup#11]
Could you please give the possibility to set an i18n-placeholdertext. At the moment der is hardcoded "Enter Search Criteria"!

Thanks

**Comment by seanthomasdevlin** [comment]
Hi ,

You can extend the default implementation forms or build your own. To change just that one property, perhaps extend svyLookupTable.frm and change the property.

See more at:
https://github.com/Servoy/svyLookup/wiki#lookup-templates

Best,
Sean

**Comment by philippr71** [comment]
Perfect, thanks Sean!
