### ISSUE TITLE
TypeError when using Lookup

### ISSUE THREAD

**Issue by j-patel** [Servoy/svyLookup#3]
On gaining and losing focus of search element and selecting a record from lookup table, following error is generated:
```
ERROR com.servoy.j2db.util.Debug - TypeError: Cannot call method "addKeyListener" of undefined (C:\Users\pc\servoy_workspace\svyLookup\forms\svyLookupTable.js#51) (Form Context: D9163E3C-9B44-4526-8AF1-D28225A3F68C), JSEvent(type = focusGained, source = Component: <searchText>, formName = D9163E3C-9B44-4526-8AF1-D28225A3F68C, elementName = searchText, timestamp = 2018-03-16 10:33:31.156,modifiers = 0,x =0,y = 0,data = null)
	at C:\Users\pc\servoy_workspace\svyLookup\forms\svyLookupTable.js:51 (onFocusGainedSearch)
```

This is because in `svyLookupTable.js`:

`plugins.keyListener.addKeyListener(elements.searchText,onKey);`

I get a warning for this:

```
The property keyListener is undefined for the type Plugins
```

**Comment by seanthomasdevlin** [comment]
Hi Jay,

This is because svyLookup has a dependency [on svyKeyListener](https://github.com/Servoy/svyKeyListener) project. This is available through the webpackages manager, under "services". After that, it should work.

**Comment by j-patel** [comment]
Thanks Sean, That worked!
