### ISSUE TITLE
function newInstance(lookupObj) in Forms.AbstractLookup create a formName with UUID than has '-'  chars

### ISSUE THREAD

**Issue by jmlpinaEtec** [Servoy/svyLookup#8]
Hi. 
the function newInstance(lookupObj) in Forms.AbstractLookup create a form that show a warm in the log of servoyServer.

WARN com.servoy.j2db.util.Debug - The name 'D016AE88-5BF5-48B9-84BA-CBF239DA08EC' is not a valid indentifier for a component/form, please change this (avoid '-' or other invalid chars, replace those with '_', also can't start with a number), replacement could be: 'D016AE88_5BF5_48B9_84BA_CBF239DA08EC'
	at C:\WorkspaceServoy2020.06\svyLookup\forms\AbstractLookup.js:374 (newInstance)
	at C:\WorkspaceServoy2020.06\svyLookup\svyLookup.js:921
	at C:\WorkspaceServoy2020.06\svyPopupFilter\svyPopupFilter.js:851
	at C:\WorkspaceServoy2020.06\svyPopupFilter\svyToolbarFilter.js:1955
	at C:\WorkspaceServoy2020.06\svyPopupFilter\svyToolbarFilter.js:2294
	at C:\WorkspaceGit\Servoy\set_navegacion\forms\sn_ng_popupfilter.js:48 (onListComponentClick)

Thanks

**Comment by pruhsert** [comment]
That should already been fixed with https://github.com/Servoy/svyLookup/commit/99c0e7db4962b5eb71067bb9dc6d1aa30b443ad3

Will be available in the next release.
